### ISSUE TITLE
Adjustable timeout for write call

### ISSUE THREAD

**Issue by henrikno** [iZettle/dropwizard-metrics-influxdb#31]
The write call has a timeout hardcoded at 1 second
```
        con.setConnectTimeout(1000);
        con.setReadTimeout(1000);
```
This happens to be just a bit too low for us (lots of metrics), which gives timeout for every write.
The write is still going through (backend doesn't know the client has timed out), so all the data is there, there's just a lot of log messages like these:
```
2015-12-07 23:59:35,975 [WARN] [class=c.i.m.i.InfluxDbReporter] [thread=metrics-influxDb-reporter-1-thread-1]: Unable to report to InfluxDB. Discarding data.
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_31]
        at java.net.SocketInputStream.read(SocketInputStream.java:150) ~[na:1.8.0_31]
        at java.net.SocketInputStream.read(SocketInputStream.java:121) ~[na:1.8.0_31]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_31]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_31]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_31]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:703) ~[na:1.8.0_31]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_31]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535) ~[na:1.8.0_31]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_31]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_31]
        at com.izettle.metrics.influxdb.InfluxDbHttpSender.writeData(InfluxDbHttpSender.java:89) ~[metrics-influxdb-1.0.7.jar:1.0.7]
        at com.izettle.metrics.influxdb.InfluxDbReporter.report(InfluxDbReporter.java:228) ~[metrics-influxdb-1.0.7.jar:1.0.7]
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162) [metrics-core-3.1.2.jar:3.1.2]
        at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117) [metrics-core-3.1.2.jar:3.1.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_31]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_31]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_31]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

Making the timout values adjustable would fix this for us.

**Comment by nzroller** [comment]
Hi @henrikno -- firstly apologies for not replying earlier on this! We will look into making it configurable next week.
